### ISSUE TITLE
安裝問題

### ISSUE THREAD

**Issue by A51137** [inmny/Cultivation-Way-Core#2]
我目前嘗試了
1.把latest的CW_Core-v1.0.5丟入mod文件夾 但是ncms沒辦法抓到
2.我載了code的Cultivation-Way-Core-main 但是我看不懂安裝的第3步要怎麼操作

**Comment by A51137** [comment]
Cultivation-Way-Core-main 我的ncms有偵測到但是在遊戲裡沒有 模組的頁面

**Comment by inmny** [comment]
请问游戏的版本? v1.0.5适用于0.14.*的游戏版本.

由于个人原因, 最新的commit已迁移至从NeoModLoader加载， 而不支持从NCMS加载, 而README中的安装方法未更新（仓库太凉了, 就懒得开新分支处理）. 

对于你的情况, 较为推荐的是从[该commit](https://github.com/inmny/Cultivation-Way-Core/tree/0be49f66556d5e611802b83f4d6f24af96044eb4)直接下载作为普通的NCMS模组安装.

实在抱歉.

**Comment by A51137** [comment]
原來如此，我現在是使用最新的遊戲版本感謝大老抽空回答。
